### ISSUE TITLE
Resources Time Warning

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/esx_menu_default#10]
I'm using the lastest build of FiveM (804)
Reinstalled every script clean without any modification in the script itself
Modified only the css of esx_menu_default to change the form and color of title
But now.. when we switch fast in the menu there is a resources time warning.. what could be causing this ?

https://imgur.com/rja3vmi

**Comment by blackflash01** [comment]
the same for , since last client build .

**Comment by Dragese** [comment]
same problem

**Comment by sitamCZ** [comment]
I can confirm same problem, even tried with latest server binaries.

**Comment by Syntasu** [comment]
confirmed, having the same issue.

**Comment by Xseba360** [comment]
Can confirm this as well.

**Comment by ElPumpo** [comment]
Duplicate of #5
