### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by benzon** [ESX-Org/esx_menu_default#15]
The current version of esx_menu_default is causing a memory leak, ex. if you hold down your arrow buttons in esx_skin it will cause that to use +50mb of ram.

Tryed an older version that gives the ms warning of esx_menu_default but that dos not cause issues. besides the ms warning.

**Comment by benzon** [comment]
I think it might be the new call back method thats broken from fivem's side not sure that method is worth using.

**Comment by ElPumpo** [comment]
Problem with esx_skin and not this
