### ISSUE TITLE
error js at line 64

### ISSUE THREAD

**Issue by le-pet** [ESX-Org/esx_menu_default#4]
i have a error at the line 64 when i open esx_billing
he says error js at line 64 cannot read property 'scrollIntoView' of undefined

**Comment by mrdigital0** [comment]
i have this same issue but its on other menus (almost all of them and some refuse to show)

**Comment by SirMarkNL** [comment]
Same here: 
nui://esx_menu_default/html/js/app.js:64, Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined.

**Comment by zarx1337** [comment]
I have it too

**Comment by amerem3** [comment]
I also have this So my esx_shops don't work

**Comment by movierelics** [comment]
Yes, this is affecting esx_shops, esx_weashops, etc... nui://esx_menu_default/html/js/app.js:64, Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined.

Anyone with an idea how to fix this would be very helpful.

**Comment by Tanoshi-Shinto** [comment]
just go into the js file and remove .scrollIntoView() that's the easy way of getting rid of the errors. or if you know .js which my guess is most here don't redo that line

**Comment by Yoda29** [comment]
I have remote  .scrollIntoView() but it doesn't work ^^

**Comment by GeoZzNL** [comment]
2019 still this issue! Updates versions esx

**Comment by marknx** [comment]
same here

**Comment by cwc02777** [comment]
Hey guys~  i think i found the way to fix this problem 
you should check the folder name of some problem plugins in resources
they can't have version

EX.   "esx_shops"  the name like this can be work will
but named like  "esx_shops-1.0.0" can't work   
hope for help

sorry for my english

**Comment by Zeedfy** [comment]
hi, anyone knows how to fix it? I get the same error

**Comment by Yarpii-Tech** [comment]
kinda funny that the creator of the script does not come with solution even when so many people having this issue... 
it's mid 2019 and well still not fixed when this issue has been mention in 6 Mar 2018

**Comment by Cruzetch** [comment]
that removes the error but still doesnt fix the menu

**Comment by numpty9989** [comment]
agree it gets rid of that error and produces another error :(
`nui://esx_menu_default/html/js/app.js:74, Uncaught TypeError: Cannot convert undefined or  null to object`
`nui://esx_menu_default/html/js/app.js:69, Uncaught ReferenceError: id is not defined`

any help fixing this at all is appreciated as its breaking any form of RP by not able to use shops or Weapons shops :(

**Comment by prouargegamer** [comment]
is this fixed yet?

**Comment by NyboTV** [comment]
05.16.2021 Still not fixed.

**Comment by WLVF** [comment]
> 05.16.2021 Still not fixed.

ikr...

**Comment by RavenHart1** [comment]
![1](https://user-images.githubusercontent.com/72522139/121103518-1ede2f00-c7ce-11eb-883e-a547aad9022b.png)

gives me this error then i try to use the get item option in the fridges of my jobs or vaults.. -_-  can't find a solution either ... im getting sick of it
