### ISSUE TITLE
Span bug

### ISSUE THREAD

**Issue by SoldiertsuNami** [ESX-Org/esx_menu_default#8]
image: https://i.imgur.com/qY9Aepx.jpg
i try to close the first span and same error i don't know why :'(
image 2: https://i.imgur.com/oHNqP7o.jpg

i'm using the default menu and the esx_lscustom

**Comment by SoldiertsuNami** [comment]
Done it just remove comment from 
ui.html

**Comment by RanerRU** [comment]
I have the same problem now, and sorry, but for me your explanation wasn't clear. Can you take a print or something like that to show me?
